### ISSUE TITLE
Secure password field entry.

### ISSUE THREAD

**Issue by chrisidefix** [sunekaae/bean-on-the-screen#1]
Technically, all works well currently with the password entry, but the password field itself should probably have the "Secure Text Entry" flag enabled. I can understand that it makes sense to have it readable, but people expect to have their password "hidden" upon entry I believe.

Also would enable the flag "Clear when editing begins" flag for additional comfort.

**Comment by sunekaae** [comment]
PR from Christ fixed it :)
